import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`bg-slate-200 h-screen
         ${inter.className}`}
      >
        <header className='p-8 bg-blue-300'>
          <div className='max-w-[1200px] mx-auto'>
            <h1>BlogKori</h1>
          </div>
        </header>
        <main className='max-w-[1200px] mx-auto bg-white min-h-full p-8'>
          {children}
        </main>
      </body>
    </html>
  )
}
